alter table public.profiles add column accepting_new_conversations boolean not null default true;
alter table public.profiles add column introduction_scope text not null default 'everyone' check (introduction_scope in ('everyone', 'matching_preferences', 'verified_only', 'nobody'));
create table public.conversation_introductions (
  conversation_id uuid primary key references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  normalized_hash text not null,
  created_at timestamptz not null default now()
);
alter table public.conversation_introductions enable row level security;
create policy "Participants read introductions" on public.conversation_introductions for select to authenticated using (sender_id = (select auth.uid()) or recipient_id = (select auth.uid()));
drop policy if exists "Participants send messages" on public.messages;
create policy "Participants send messages" on public.messages for insert to authenticated with check (sender_id = (select auth.uid()) and public.is_conversation_participant(conversation_id));

create or replace function public.start_conversation(other_user uuid, introduction text default '') returns uuid language plpgsql security definer set search_path = public as $$ declare conversation_id uuid; me uuid := auth.uid(); recipient_accepts boolean; recipient_scope text; intro text := left(trim(coalesce(introduction, '')), 2000); intro_hash text := md5(regexp_replace(lower(intro), '\s+', ' ', 'g')); begin if me is null or me = other_user then raise exception 'Invalid participant'; end if; select accepting_new_conversations, introduction_scope into recipient_accepts, recipient_scope from public.profiles where id = other_user; if recipient_accepts is null then raise exception 'Profile unavailable'; end if; select cp.conversation_id into conversation_id from public.conversation_participants cp join public.conversation_participants cp2 on cp2.conversation_id = cp.conversation_id where cp.user_id = me and cp2.user_id = other_user limit 1; if conversation_id is not null then return conversation_id; end if; if not recipient_accepts or recipient_scope = 'nobody' then raise exception 'This user is not accepting new conversations'; end if; if exists (select 1 from public.profile_blocks where (blocker_id = me and blocked_id = other_user) or (blocker_id = other_user and blocked_id = me)) then raise exception 'Conversation unavailable'; end if; if (select count(*) from public.conversation_introductions where sender_id = me and created_at > now() - interval '1 hour') >= 10 then raise exception 'Introduction rate limit reached'; end if; if intro <> '' and (select count(distinct recipient_id) from public.conversation_introductions where sender_id = me and normalized_hash = intro_hash and created_at > now() - interval '24 hours') >= 3 then raise exception 'Repeated introduction blocked'; end if; insert into public.conversations default values returning id into conversation_id; insert into public.conversation_participants values (conversation_id, me, now()), (conversation_id, other_user, null); insert into public.response_opportunities (conversation_id, initiator_id, recipient_id) values (conversation_id, me, other_user); insert into public.conversation_introductions (conversation_id, sender_id, recipient_id, body, normalized_hash) values (conversation_id, me, other_user, intro, intro_hash); return conversation_id; end; $$;
