-- Support Inbox foundation.  Support tickets are deliberately separate from
-- moderation cases: the same staff can work both queues, but their workflows,
-- statuses, and evidence remain independent.

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity (start with 1000) unique,
  ticket_type text not null default 'general' check (char_length(btrim(ticket_type)) between 1 and 64),
  subject text not null check (char_length(btrim(subject)) between 1 and 200),
  requester_id uuid references public.profiles(id) on delete set null,
  category text not null default 'other' check (category in ('account_access','profile','communication','snail_mail','privacy_safety','bug_report','feedback','other')),
  status text not null default 'open' check (status in ('open','waiting_staff','waiting_user','resolved')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_staff_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  body text not null check (char_length(btrim(body)) between 1 and 4000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists support_tickets_queue_idx
  on public.support_tickets(status, priority, updated_at desc);
create index if not exists support_tickets_assignment_idx
  on public.support_tickets(assigned_staff_id, status, updated_at desc);
create index if not exists support_tickets_requester_idx
  on public.support_tickets(requester_id, created_at desc);
create index if not exists support_ticket_messages_ticket_idx
  on public.support_ticket_messages(ticket_id, created_at asc);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;
revoke all on table public.support_tickets from public, anon, authenticated;
revoke all on table public.support_ticket_messages from public, anon, authenticated;

drop trigger if exists support_tickets_updated_at on public.support_tickets;
create trigger support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

create or replace function public.staff_support_open_count()
returns bigint
language sql
security definer
stable
set search_path = pg_catalog, public
as $$
  select case when public.is_moderator()
    then (select count(*) from public.support_tickets where status <> 'resolved')
    else 0::bigint
  end
$$;

revoke all on function public.staff_support_open_count() from public, anon, authenticated;
grant execute on function public.staff_support_open_count() to authenticated;

create or replace function public.staff_list_support_tickets(
  status_filter text default null,
  category_filter text default null,
  assignment_filter text default null,
  search_query text default null,
  sort_order text default 'updated_desc',
  page_size integer default 25,
  page_offset integer default 0
)
returns table (
  id uuid,
  ticket_number bigint,
  ticket_code text,
  ticket_type text,
  subject text,
  requester_id uuid,
  requester_username text,
  requester_display_name text,
  category text,
  status text,
  priority text,
  assigned_staff_id uuid,
  assigned_staff_name text,
  created_at timestamptz,
  updated_at timestamptz,
  last_message_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = pg_catalog, public
as $$
declare
  clean_status text := nullif(lower(btrim(status_filter)), '');
  clean_category text := nullif(lower(btrim(category_filter)), '');
  clean_assignment text := nullif(lower(btrim(assignment_filter)), '');
  clean_search text := nullif(btrim(search_query), '');
  clean_sort text := lower(coalesce(nullif(btrim(sort_order), ''), 'updated_desc'));
begin
  if not public.is_moderator() then
    raise exception 'Moderator authorization required';
  end if;

  if clean_status is not null and clean_status not in ('all','open','waiting_staff','waiting_user','resolved','mine','unassigned') then
    raise exception 'Unsupported support ticket status filter';
  end if;
  if clean_category is not null and clean_category not in ('account_access','profile','communication','snail_mail','privacy_safety','bug_report','feedback','other') then
    raise exception 'Unsupported support ticket category filter';
  end if;
  if clean_assignment is not null and clean_assignment not in ('all','mine','unassigned') then
    begin
      perform clean_assignment::uuid;
    exception when invalid_text_representation then
      raise exception 'Unsupported support ticket assignment filter';
    end;
  end if;
  if clean_sort not in ('updated_desc','updated_asc','created_desc','priority_desc') then
    raise exception 'Unsupported support ticket sort';
  end if;

  page_size := least(greatest(coalesce(page_size, 25), 1), 100);
  page_offset := greatest(coalesce(page_offset, 0), 0);

  return query
  select t.id,
         t.ticket_number,
         ('SUP-' || t.ticket_number)::text,
         t.ticket_type,
         t.subject,
         t.requester_id,
         requester.username,
         requester.display_name,
         t.category,
         t.status,
         t.priority,
         t.assigned_staff_id,
         assigned.display_name,
         t.created_at,
         t.updated_at,
         latest_message.created_at,
         count(*) over ()
    from public.support_tickets t
    left join public.profiles requester on requester.id = t.requester_id
    left join public.profiles assigned on assigned.id = t.assigned_staff_id
    left join lateral (
      select m.created_at
        from public.support_ticket_messages m
       where m.ticket_id = t.id
       order by m.created_at desc
       limit 1
    ) latest_message on true
   where (clean_status is null or clean_status = 'all'
      or (clean_status = 'open' and t.status <> 'resolved')
      or (clean_status = 'mine' and t.assigned_staff_id = auth.uid())
      or (clean_status = 'unassigned' and t.assigned_staff_id is null)
      or t.status = clean_status)
     and (clean_category is null or t.category = clean_category)
     and (clean_assignment is null or clean_assignment = 'all'
      or (clean_assignment = 'mine' and t.assigned_staff_id = auth.uid())
      or (clean_assignment = 'unassigned' and t.assigned_staff_id is null)
      or (case when clean_assignment not in ('all','mine','unassigned') then clean_assignment::uuid end = t.assigned_staff_id))
     and (clean_search is null
      or t.subject ilike '%' || clean_search || '%'
      or ('SUP-' || t.ticket_number)::text ilike '%' || clean_search || '%'
      or requester.username ilike '%' || clean_search || '%'
      or requester.display_name ilike '%' || clean_search || '%')
   order by
     case when clean_sort = 'priority_desc' then case t.priority when 'urgent' then 0 when 'high' then 1 when 'normal' then 2 else 3 end end asc nulls last,
     case when clean_sort = 'updated_asc' then t.updated_at end asc nulls last,
     case when clean_sort = 'created_desc' then t.created_at end desc nulls last,
     case when clean_sort in ('updated_desc','priority_desc') then t.updated_at end desc nulls last,
     t.id
   limit page_size offset page_offset;
end;
$$;

revoke all on function public.staff_list_support_tickets(text, text, text, text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.staff_list_support_tickets(text, text, text, text, text, integer, integer) to authenticated;

create or replace function public.staff_get_support_ticket(ticket_uuid uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = pg_catalog, public
as $$
declare
  result jsonb;
begin
  if not public.is_moderator() then
    raise exception 'Moderator authorization required';
  end if;

  select jsonb_build_object(
    'ticket', jsonb_build_object(
      'id', t.id,
      'ticket_number', t.ticket_number,
      'ticket_code', 'SUP-' || t.ticket_number,
      'ticket_type', t.ticket_type,
      'subject', t.subject,
      'category', t.category,
      'status', t.status,
      'priority', t.priority,
      'created_at', t.created_at,
      'updated_at', t.updated_at,
      'resolved_at', t.resolved_at,
      'requester', case when t.requester_id is null then null else jsonb_build_object(
        'id', t.requester_id, 'username', requester.username, 'display_name', requester.display_name
      ) end,
      'assigned_staff', case when t.assigned_staff_id is null then null else jsonb_build_object(
        'id', t.assigned_staff_id, 'display_name', assigned.display_name
      ) end
    ),
    'messages', coalesce((select jsonb_agg(jsonb_build_object(
      'id', m.id,
      'author_id', m.author_id,
      'author_name', coalesce(author.display_name, author.username, 'Former account'),
      'body', m.body,
      'is_internal', m.is_internal,
      'created_at', m.created_at
    ) order by m.created_at asc)
      from public.support_ticket_messages m
      left join public.profiles author on author.id = m.author_id
     where m.ticket_id = t.id), '[]'::jsonb)
  ) into result
    from public.support_tickets t
    left join public.profiles requester on requester.id = t.requester_id
    left join public.profiles assigned on assigned.id = t.assigned_staff_id
   where t.id = ticket_uuid;

  return result;
end;
$$;

revoke all on function public.staff_get_support_ticket(uuid) from public, anon, authenticated;
grant execute on function public.staff_get_support_ticket(uuid) to authenticated;
