alter table public.conversation_introductions rename column conversation_id to conversation_id_legacy;
alter table public.conversation_introductions drop constraint if exists conversation_introductions_pkey;
alter table public.conversation_introductions alter column conversation_id_legacy drop not null;
alter table public.conversation_introductions add column id uuid not null default gen_random_uuid() primary key;
alter table public.conversation_introductions add column icebreaker text not null default '';
alter table public.conversation_introductions add column expires_at timestamptz not null default (now() + interval '7 days');
alter table public.conversation_introductions add column status text not null default 'replied' check (status in ('pending','replied','declined','expired'));
alter table public.conversation_introductions add constraint introduction_icebreaker_length check (icebreaker = '' or char_length(icebreaker) between 30 and 500);
create unique index one_active_introduction on public.conversation_introductions (sender_id, recipient_id) where status = 'pending';
create index introductions_recipient_status_idx on public.conversation_introductions (recipient_id, status, created_at desc);

create or replace function public.expire_introductions() returns void language sql security definer set search_path = public as $$ update public.conversation_introductions set status = 'expired' where status = 'pending' and expires_at <= now() $$;
revoke all on function public.expire_introductions() from public;
grant execute on function public.expire_introductions() to authenticated;

create or replace function public.submit_introduction(other_user uuid, introduction text) returns uuid language plpgsql security definer set search_path = public as $$ declare intro_id uuid; me uuid := auth.uid(); recipient_accepts boolean; recipient_scope text; body text := trim(coalesce(introduction, '')); body_hash text := md5(regexp_replace(lower(body), '\s+', ' ', 'g')); begin perform public.expire_introductions(); if me is null or me = other_user then raise exception 'Invalid participant'; end if; if char_length(body) < 30 or char_length(body) > 500 then raise exception 'Icebreaker must be 30 to 500 characters'; end if; select accepting_new_conversations, introduction_scope into recipient_accepts, recipient_scope from public.profiles where id = other_user; if recipient_accepts is null or not recipient_accepts or recipient_scope = 'nobody' then raise exception 'This user is not accepting new conversations'; end if; if exists (select 1 from public.profile_blocks where (blocker_id = me and blocked_id = other_user) or (blocker_id = other_user and blocked_id = me)) then raise exception 'Conversation unavailable'; end if; if exists (select 1 from public.conversation_participants cp join public.conversation_participants cp2 on cp2.conversation_id = cp.conversation_id where cp.user_id = me and cp2.user_id = other_user) then raise exception 'Conversation already exists'; end if; if exists (select 1 from public.conversation_introductions where sender_id = me and recipient_id = other_user and status = 'pending') then raise exception 'Introduction already pending'; end if; if (select count(*) from public.conversation_introductions where sender_id = me and created_at > now() - interval '1 hour') >= 10 then raise exception 'Introduction rate limit reached'; end if; if (select count(distinct recipient_id) from public.conversation_introductions where sender_id = me and normalized_hash = body_hash and created_at > now() - interval '24 hours') >= 3 then raise exception 'Repeated introduction blocked'; end if; insert into public.conversation_introductions (sender_id, recipient_id, body, normalized_hash, icebreaker, expires_at, status) values (me, other_user, body, body_hash, body, now() + interval '7 days', 'pending') returning id into intro_id; return intro_id; end; $$;
revoke all on function public.submit_introduction(uuid, text) from public;
grant execute on function public.submit_introduction(uuid, text) to authenticated;

create or replace function public.reply_to_introduction(introduction_id uuid, reply text) returns uuid language plpgsql security definer set search_path = public as $$ declare intro public.conversation_introductions; conversation_id uuid; me uuid := auth.uid(); body text := trim(coalesce(reply, '')); begin perform public.expire_introductions(); if me is null or char_length(body) = 0 or char_length(body) > 2000 then raise exception 'Invalid reply'; end if; select * into intro from public.conversation_introductions where id = introduction_id for update; if intro.id is null or intro.recipient_id <> me or intro.status <> 'pending' or intro.expires_at <= now() then raise exception 'Introduction is no longer available'; end if; if exists (select 1 from public.profile_blocks where (blocker_id = me and blocked_id = intro.sender_id) or (blocker_id = intro.sender_id and blocked_id = me)) then raise exception 'Conversation unavailable'; end if; insert into public.conversations default values returning id into conversation_id; insert into public.conversation_participants values (conversation_id, intro.sender_id, null), (conversation_id, intro.recipient_id, now()); insert into public.messages (conversation_id, sender_id, body) values (conversation_id, intro.sender_id, intro.icebreaker), (conversation_id, me, body); update public.conversation_introductions set status = 'replied', conversation_id_legacy = conversation_id where id = introduction_id; return conversation_id; end; $$;
revoke all on function public.reply_to_introduction(uuid, text) from public;
grant execute on function public.reply_to_introduction(uuid, text) to authenticated;

create or replace function public.decline_introduction(introduction_id uuid) returns void language plpgsql security definer set search_path = public as $$ begin perform public.expire_introductions(); update public.conversation_introductions set status = 'declined' where id = introduction_id and recipient_id = auth.uid() and status = 'pending'; if not found then raise exception 'Introduction is no longer available'; end if; end; $$;
revoke all on function public.decline_introduction(uuid) from public;
grant execute on function public.decline_introduction(uuid) to authenticated;

create or replace function public.get_response_stats(target_user uuid) returns table (completed_opportunities bigint, response_rate numeric, median_hours numeric) language sql security definer set search_path = public as $$ with valid as (select i.* from public.conversation_introductions i where i.recipient_id = target_user and i.status in ('replied','declined','expired') and not exists (select 1 from public.profile_blocks b where (b.blocker_id = i.sender_id and b.blocked_id = i.recipient_id) or (b.blocker_id = i.recipient_id and b.blocked_id = i.sender_id))), stats as (select count(*) as completed, count(*) filter (where status in ('replied','declined')) as handled, percentile_cont(0.5) within group (order by extract(epoch from ((case when status = 'replied' then coalesce((select min(m.created_at) from public.messages m where m.conversation_id = valid.conversation_id_legacy and m.sender_id = valid.recipient_id), created_at) else created_at end) - created_at)) / 3600.0) filter (where status in ('replied','declined')) as median from valid) select completed, case when completed >= 5 then round(handled::numeric * 100 / completed, 0) else null end, median from stats $$;
