-- Support submission confirmation and idempotency. A submission token is
-- generated by the form and consumed only for the authenticated requester.

alter table public.support_tickets
  add column if not exists submission_token uuid;

create unique index if not exists support_tickets_submission_token_idx
  on public.support_tickets(requester_id, submission_token)
  where submission_token is not null;

drop function if exists public.submit_support_ticket(text, text, text, jsonb);

create or replace function public.submit_support_ticket(
  p_category text,
  p_subject text,
  p_description text,
  p_attachments jsonb,
  p_submission_token uuid
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  me uuid := auth.uid();
  clean_category text := lower(btrim(coalesce(p_category, '')));
  clean_subject text := btrim(coalesce(p_subject, ''));
  clean_description text := btrim(coalesce(p_description, ''));
  ticket_id uuid;
  attachment jsonb;
  attachment_path text;
  attachment_name text;
  attachment_type text;
  attachment_size bigint;
begin
  if me is null or not public.is_email_verified() then
    raise exception 'Verified account required';
  end if;

  if exists (select 1 from public.profiles where id = me and deactivated_at is not null) then
    raise exception 'Account unavailable';
  end if;

  if p_submission_token is not null then
    select id into ticket_id
      from public.support_tickets
     where requester_id = me and submission_token = p_submission_token;
    if ticket_id is not null then
      return ticket_id;
    end if;
  end if;

  if clean_category not in ('account_access', 'profile', 'communication', 'snail_mail', 'privacy_safety', 'bug_report', 'feedback', 'other') then
    raise exception 'Invalid support category';
  end if;
  if char_length(clean_subject) < 3 or char_length(clean_subject) > 200 then
    raise exception 'Support subject must be 3 to 200 characters';
  end if;
  if char_length(clean_description) < 10 or char_length(clean_description) > 4000 then
    raise exception 'Support description must be 10 to 4000 characters';
  end if;
  if jsonb_typeof(coalesce(p_attachments, '[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_attachments, '[]'::jsonb)) > 3 then
    raise exception 'You can attach up to 3 files';
  end if;

  for attachment in select value from jsonb_array_elements(coalesce(p_attachments, '[]'::jsonb)) loop
    if jsonb_typeof(attachment) <> 'object' then
      raise exception 'Invalid support attachment';
    end if;
    attachment_path := btrim(coalesce(attachment->>'storage_path', ''));
    attachment_name := btrim(coalesce(attachment->>'file_name', ''));
    attachment_type := lower(btrim(coalesce(attachment->>'mime_type', '')));
    begin
      attachment_size := (attachment->>'size_bytes')::bigint;
    exception when invalid_text_representation then
      raise exception 'Invalid support attachment size';
    end;
    if split_part(attachment_path, '/', 1) <> me::text
       or not exists (select 1 from storage.objects where bucket_id = 'support-attachments' and name = attachment_path) then
      raise exception 'Invalid support attachment path';
    end if;
    if char_length(attachment_name) < 1 or char_length(attachment_name) > 200
       or attachment_type not in ('application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'text/plain')
       or attachment_size is null or attachment_size <= 0 or attachment_size > 10485760 then
      raise exception 'Invalid support attachment';
    end if;
  end loop;

  insert into public.support_tickets (subject, requester_id, category, status, priority, submission_token)
  values (clean_subject, me, clean_category, 'open', 'normal', p_submission_token)
  on conflict (requester_id, submission_token) where submission_token is not null do nothing
  returning id into ticket_id;

  if ticket_id is null then
    select id into ticket_id
      from public.support_tickets
     where requester_id = me and submission_token = p_submission_token;
    if ticket_id is null then
      raise exception 'Support request could not be created';
    end if;
    return ticket_id;
  end if;

  insert into public.support_ticket_messages (ticket_id, author_id, body, is_internal)
  values (ticket_id, me, clean_description, false);

  for attachment in select value from jsonb_array_elements(coalesce(p_attachments, '[]'::jsonb)) loop
    insert into public.support_ticket_attachments (ticket_id, uploaded_by, storage_path, file_name, mime_type, size_bytes)
    values (
      ticket_id,
      me,
      btrim(attachment->>'storage_path'),
      btrim(attachment->>'file_name'),
      lower(btrim(attachment->>'mime_type')),
      (attachment->>'size_bytes')::bigint
    );
  end loop;

  return ticket_id;
end;
$$;

-- Preserve the existing four-argument RPC for compatibility with older callers.
create or replace function public.submit_support_ticket(
  p_category text,
  p_subject text,
  p_description text,
  p_attachments jsonb default '[]'::jsonb
)
returns uuid
language sql
security definer
set search_path = pg_catalog, public
as $$
  select public.submit_support_ticket(p_category, p_subject, p_description, p_attachments, null::uuid)
$$;

revoke all on function public.submit_support_ticket(text, text, text, jsonb, uuid) from public, anon, authenticated;
grant execute on function public.submit_support_ticket(text, text, text, jsonb, uuid) to authenticated;
revoke all on function public.submit_support_ticket(text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.submit_support_ticket(text, text, text, jsonb) to authenticated;

create or replace function public.get_my_support_ticket_confirmation(ticket_uuid uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = pg_catalog, public
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null or not public.is_email_verified() then
    raise exception 'Verified account required';
  end if;

  select jsonb_build_object(
    'id', t.id,
    'ticket_code', 'SUP-' || t.ticket_number,
    'subject', t.subject,
    'status', t.status,
    'created_at', t.created_at
  ) into result
    from public.support_tickets t
   where t.id = ticket_uuid and t.requester_id = me;

  return result;
end;
$$;

revoke all on function public.get_my_support_ticket_confirmation(uuid) from public, anon, authenticated;
grant execute on function public.get_my_support_ticket_confirmation(uuid) to authenticated;
