-- Expand the shared language catalogue with a curated set of widely
-- recognized languages. Existing names and IDs remain unchanged.

insert into public.languages (name) values
  ('Arabic'),
  ('Bengali'),
  ('Bulgarian'),
  ('Chinese'),
  ('Czech'),
  ('Danish'),
  ('Dutch'),
  ('English'),
  ('Finnish'),
  ('French'),
  ('German'),
  ('Greek'),
  ('Hebrew'),
  ('Hindi'),
  ('Hungarian'),
  ('Icelandic'),
  ('Indonesian'),
  ('Italian'),
  ('Japanese'),
  ('Korean'),
  ('Malay'),
  ('Norwegian'),
  ('Persian'),
  ('Polish'),
  ('Portuguese'),
  ('Romanian'),
  ('Russian'),
  ('Slovak'),
  ('Spanish'),
  ('Swedish'),
  ('Tagalog'),
  ('Thai'),
  ('Turkish'),
  ('Ukrainian'),
  ('Urdu'),
  ('Vietnamese'),
  ('Swahili')
on conflict (name) do nothing;
