create table public.direct_conversation_pairs (user_a uuid not null references public.profiles(id) on delete cascade, user_b uuid not null references public.profiles(id) on delete cascade, conversation_id uuid not null unique references public.conversations(id) on delete cascade, primary key (user_a, user_b), check (user_a < user_b));
insert into public.direct_conversation_pairs (user_a, user_b, conversation_id) select least(a.user_id,b.user_id), greatest(a.user_id,b.user_id), a.conversation_id from public.conversation_participants a join public.conversation_participants b on b.conversation_id=a.conversation_id and a.user_id<b.user_id on conflict do nothing;
alter table public.direct_conversation_pairs enable row level security;
create policy "Participants read direct pair" on public.direct_conversation_pairs for select to authenticated using (user_a = auth.uid() or user_b = auth.uid());

create or replace function public.submit_introduction(other_user uuid, introduction text) returns uuid language plpgsql security definer set search_path = public as $$ declare intro_id uuid; me uuid := auth.uid(); recipient_accepts boolean; recipient_scope text; body text := trim(coalesce(introduction, '')); body_hash text := md5(regexp_replace(lower(body), '\s+', ' ', 'g')); begin perform public.expire_introductions(); if me is null or me = other_user or exists (select 1 from public.profiles where id = me and deactivated_at is not null) then raise exception 'Invalid participant'; end if; if char_length(body) < 50 or char_length(body) > 500 or body !~ '^[[:alnum:]].*[[:alnum:]]$' or (select count(*) from regexp_split_to_table(body, '\s+') as words) < 8 then raise exception 'Icebreaker must be 50 to 500 characters and at least 8 words'; end if; select accepting_new_conversations, introduction_scope into recipient_accepts, recipient_scope from public.profiles where id = other_user and deactivated_at is null; if recipient_accepts is null or not recipient_accepts or recipient_scope = 'nobody' then raise exception 'This user is not accepting new conversations'; end if; if exists (select 1 from public.profile_blocks where (blocker_id = me and blocked_id = other_user) or (blocker_id = other_user and blocked_id = me)) then raise exception 'Conversation unavailable'; end if; if exists (select 1 from public.direct_conversation_pairs where user_a = least(me,other_user) and user_b = greatest(me,other_user)) or exists (select 1 from public.conversation_participants cp join public.conversation_participants cp2 on cp2.conversation_id=cp.conversation_id where cp.user_id=me and cp2.user_id=other_user) then raise exception 'Conversation already exists'; end if; if exists (select 1 from public.conversation_introductions where sender_id=me and recipient_id=other_user and status='pending') then raise exception 'Introduction already pending'; end if; if (select count(*) from public.conversation_introductions where sender_id=me and created_at > now()-interval '1 hour') >= 10 then raise exception 'Introduction rate limit reached'; end if; if (select count(distinct recipient_id) from public.conversation_introductions where sender_id=me and normalized_hash=body_hash and created_at > now()-interval '24 hours') >= 3 then raise exception 'Repeated introduction blocked'; end if; insert into public.conversation_introductions(sender_id,recipient_id,body,normalized_hash,icebreaker,expires_at,status) values(me,other_user,body,body_hash,body,now()+interval '7 days','pending') returning id into intro_id; return intro_id; end; $$;

create or replace function public.reply_to_introduction(introduction_id uuid, reply text) returns uuid language plpgsql security definer set search_path = public as $$ declare intro public.conversation_introductions; existing_conversation_id uuid; me uuid := auth.uid(); body text := trim(coalesce(reply,'')); a uuid; b uuid; begin perform public.expire_introductions(); if me is null or char_length(body)=0 or char_length(body)>2000 or exists (select 1 from public.profiles where id=me and deactivated_at is not null) then raise exception 'Invalid reply'; end if; select * into intro from public.conversation_introductions where id=introduction_id for update; if intro.id is null or intro.recipient_id<>me or intro.status<>'pending' or intro.expires_at<=now() then raise exception 'Introduction is no longer available'; end if; if exists (select 1 from public.profiles where id in (intro.sender_id, intro.recipient_id) and deactivated_at is not null) then raise exception 'Conversation unavailable'; end if; if exists (select 1 from public.profile_blocks where (blocker_id=me and blocked_id=intro.sender_id) or (blocker_id=intro.sender_id and blocked_id=me)) then raise exception 'Conversation unavailable'; end if; a:=least(me,intro.sender_id); b:=greatest(me,intro.sender_id); perform pg_advisory_xact_lock(hashtextextended(a::text||b::text,0)); select d.conversation_id into existing_conversation_id from public.direct_conversation_pairs d where d.user_a=a and d.user_b=b; if existing_conversation_id is null then insert into public.conversations default values returning id into existing_conversation_id; insert into public.direct_conversation_pairs(user_a,user_b,conversation_id) values(a,b,existing_conversation_id) on conflict (user_a,user_b) do nothing; select d.conversation_id into existing_conversation_id from public.direct_conversation_pairs d where d.user_a=a and d.user_b=b; end if; if not exists (select 1 from public.conversation_participants cp where cp.conversation_id=existing_conversation_id and cp.user_id=me) then insert into public.conversation_participants(conversation_id,user_id,last_read_at) values(existing_conversation_id,intro.sender_id,null),(existing_conversation_id,intro.recipient_id,now()) on conflict do nothing; end if; insert into public.messages(conversation_id,sender_id,body) values(existing_conversation_id,intro.sender_id,intro.icebreaker),(existing_conversation_id,me,body); update public.conversation_introductions set status='replied',conversation_id_legacy=existing_conversation_id where id=introduction_id; return existing_conversation_id; end; $$;

drop policy if exists "Participants send messages" on public.messages;
create policy "Participants send active unblocked messages" on public.messages for insert to authenticated with check (sender_id=auth.uid() and public.is_conversation_participant(conversation_id) and not exists (select 1 from public.profiles where id=auth.uid() and deactivated_at is not null) and not exists (select 1 from public.conversation_participants p join public.profile_blocks b on (b.blocker_id=auth.uid() and b.blocked_id=p.user_id) or (b.blocker_id=p.user_id and b.blocked_id=auth.uid()) where p.conversation_id=messages.conversation_id and p.user_id<>auth.uid()));

create or replace function public.get_discover_profiles(viewer uuid default auth.uid()) returns table (id uuid,username text,display_name text,birth_date date,gender text,country text,city text,avatar_path text,last_active_at timestamptz) language sql security definer set search_path=public as $$ select p.id,p.username,p.display_name,p.birth_date,p.gender,p.country,case when p.show_city then p.city end,p.avatar_path,case when p.show_activity_status then p.last_active_at end from public.profiles p where p.id<>auth.uid() and p.deactivated_at is null and public.viewer_can_access_profile(p.id) $$;
revoke all on function public.get_discover_profiles(uuid) from public; grant execute on function public.get_discover_profiles(uuid) to authenticated;

drop function if exists public.start_conversation(uuid, text);
drop function if exists public.start_conversation(uuid);
