create table public.languages (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.interests (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.profile_languages (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  language_id bigint not null references public.languages(id) on delete restrict,
  proficiency text not null check (proficiency in ('native', 'fluent', 'intermediate', 'beginner')),
  purpose text not null check (purpose in ('speaks', 'learning')),
  primary key (profile_id, language_id, purpose)
);

create table public.profile_interests (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  primary key (profile_id, interest_id)
);

alter table public.languages enable row level security;
alter table public.interests enable row level security;
alter table public.profile_languages enable row level security;
alter table public.profile_interests enable row level security;

create policy "Authenticated users can read languages" on public.languages for select to authenticated using (true);
create policy "Authenticated users can read interests" on public.interests for select to authenticated using (true);
create policy "Authenticated users can read profile languages" on public.profile_languages for select to authenticated using (true);
create policy "Authenticated users can read profile interests" on public.profile_interests for select to authenticated using (true);
create policy "Users manage own profile languages" on public.profile_languages for all to authenticated using ((select auth.uid()) = profile_id) with check ((select auth.uid()) = profile_id);
create policy "Users manage own profile interests" on public.profile_interests for all to authenticated using ((select auth.uid()) = profile_id) with check ((select auth.uid()) = profile_id);

insert into public.languages (name) values ('Arabic'), ('Chinese'), ('English'), ('French'), ('German'), ('Hindi'), ('Italian'), ('Japanese'), ('Korean'), ('Portuguese'), ('Russian'), ('Spanish'), ('Turkish') on conflict do nothing;
insert into public.interests (name) values ('Books'), ('Cooking'), ('Culture'), ('Gaming'), ('Hiking'), ('Movies'), ('Music'), ('Photography'), ('Science'), ('Sports'), ('Technology'), ('Travel'), ('Writing'), ('Art') on conflict do nothing;
