/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import Link from "next/link";
import { requireStaff } from "../guard";
import { AdminHeader, AdminPage } from "../AdminChrome";

const actions = ["status_change", "case_created", "case_view", "case_status_change", "case_claim", "case_release", "case_reassign", "case_note_added", "conversation_review", "profile_badge_assigned", "profile_badge_removed", "automated_flag_created", "automated_flag_cleared", "automated_flag_confirmed", "automated_flag_context_view", "detection_rule_updated", "role_change", "deactivate_account", "reactivate_account", "profile_content_removed", "profile_content_restored", "security_context_view", "user_detail_view", "verification_metadata_view", "external_verification_recorded", "external_verification_revoked", "external_verification_conflict", "retention_policy_changed", "retention_hold_created", "retention_hold_released"];
const PAGE_SIZE = 50;

export default async function AdminAudit({ searchParams }: { searchParams: Promise<{ moderator_id?: string; action?: string; from?: string; to?: string; page?: string }> }) {
  const { db, role } = await requireStaff();
  const filters = await searchParams;
  const action = actions.includes(filters.action ?? "") ? filters.action : null;
  const page = Math.max(1, Number.parseInt(filters.page ?? "1", 10) || 1);
  const { data: auditRows, error } = await db.rpc("admin_list_audit_entries", { action_filter: action, actor_filter: filters.moderator_id || null, page_size: PAGE_SIZE, page_offset: (page - 1) * PAGE_SIZE, from_date: /^\d{4}-\d{2}-\d{2}$/.test(filters.from ?? "") ? filters.from : null, to_date: /^\d{4}-\d{2}-\d{2}$/.test(filters.to ?? "") ? filters.to : null });
  const rows = Array.isArray(auditRows) ? auditRows : [];
  const total = Number(rows[0]?.total_count ?? 0);
  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const linkFor = (nextPage: number) => { const params = new URLSearchParams(); if (filters.moderator_id) params.set("moderator_id", filters.moderator_id); if (action) params.set("action", action); if (filters.from) params.set("from", filters.from); if (filters.to) params.set("to", filters.to); params.set("page", String(nextPage)); return `/app/admin/audit?${params.toString()}`; };
  const ids = [...new Set(rows.flatMap((row: any) => [row.moderator_id, row.target_user_id].filter(Boolean)))];
  const people = new Map<string, any>(); let peopleError: any = null;
  if (ids.length && role === "admin") { const { data, error: profileLookupError } = await db.from("profiles").select("id,username,display_name").in("id", ids); peopleError = profileLookupError; for (const person of data ?? []) people.set(person.id, person); }
  return <AdminPage><AdminHeader active="audit" eyebrow="Accountability · Read-only" title="Audit log" description="A searchable record of moderation decisions and privileged access." isAdmin={role === "admin"} />
    <form className="admin-toolbar flex flex-wrap items-end gap-3"><label className="text-sm text-black/60">Actor ID<input name="moderator_id" defaultValue={filters.moderator_id ?? ""} className="field mt-2 block w-56" placeholder="Optional UUID" /></label><label className="text-sm text-black/60">Action<select name="action" defaultValue={action ?? ""} className="field mt-2 block w-auto"><option value="">All visible actions</option>{actions.filter((value) => role === "admin" || !["role_change", "deactivate_account", "reactivate_account", "security_context_view", "user_detail_view", "verification_metadata_view", "external_verification_recorded", "external_verification_revoked", "external_verification_conflict", "retention_policy_changed", "retention_hold_created", "retention_hold_released", "detection_rule_updated"].includes(value)).map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm text-black/60">From<input type="date" name="from" defaultValue={filters.from ?? ""} className="field mt-2 block w-auto" /></label><label className="text-sm text-black/60">To<input type="date" name="to" defaultValue={filters.to ?? ""} className="field mt-2 block w-auto" /></label><button className="btn-primary px-4 py-2.5 text-sm">Apply filters</button></form>
    {error && <p role="alert" className="notice notice-error mt-5">The audit log could not be loaded.</p>}{peopleError && <p role="alert" className="notice notice-error mt-5">Actor and target context could not be loaded. Refresh before relying on account names.</p>}
    <section className="admin-section mt-8" aria-label="Moderation audit entries">{rows.length ? <div className="admin-table">{rows.map((entry: any) => { const actor = people.get(entry.moderator_id); const target = people.get(entry.target_user_id); const reason = entry.metadata?.reason; const context = entry.metadata?.context; return <div key={entry.id} className="admin-row"><div className="flex flex-wrap items-baseline justify-between gap-3"><p className="font-medium capitalize">{entry.action.replaceAll("_", " ")}</p><time dateTime={entry.created_at} className="text-xs text-black/45">{new Date(entry.created_at).toLocaleString()}</time></div><p className="mt-2 text-sm text-black/60">{actor?.display_name ?? (entry.moderator_id ? `Actor ${entry.moderator_id.slice(0, 8)}` : "System")} · {entry.old_status ?? "—"} → {entry.new_status ?? "—"}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs">{target && <Link href={`/app/admin/users/${target.id}`} className="text-brand hover:underline">Target: {target.display_name ?? target.username}</Link>}{entry.case_id && <Link href={`/app/admin/cases/${entry.case_id}`} className="text-brand hover:underline">Case {entry.case_id.slice(0, 8)}</Link>}{entry.report_id && <Link href={`/app/admin/reports?report=${entry.report_id}`} className="text-brand hover:underline">Report {entry.report_id.slice(0, 8)}</Link>}</div>{(reason || context) && <details className="mt-3 text-xs text-black/55"><summary className="cursor-pointer font-semibold text-brand">Details</summary>{reason && <p className="mt-2">Reason: {String(reason)}</p>}{context && <p className="mt-1">Context: {String(context)}</p>}</details>}</div>; })}</div> : <p className="border-t border-black/10 py-10 text-sm text-black/50">No audit entries match these filters.</p>}</section>
    <nav className="mt-6 flex items-center justify-between border-t border-black/10 pt-5 text-sm" aria-label="Audit pagination"><span className="text-black/50">Page {page} of {pageCount}</span><div className="flex gap-4">{page > 1 && <Link href={linkFor(page - 1)} className="text-brand hover:underline">Previous</Link>}{page < pageCount && <Link href={linkFor(page + 1)} className="text-brand hover:underline">Next</Link>}</div></nav>
  </AdminPage>;
}
