/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { requireAdmin } from "./guard";
import { AdminHeader, AdminPage, StatusChip, toneForStatus } from "./AdminChrome";

export default async function AdminCenter() {
  const { db } = await requireAdmin();
  const today = new Date().toISOString().slice(0, 10);
  const [{ data: summary, error: summaryError }, { data: recentReports, error: reportsError }, { data: auditRows, error: auditError }, { data: todayAnalytics, error: analyticsError }] = await Promise.all([
    db.rpc("admin_dashboard_summary"),
    db.from("reports").select("id,target_type,reason,status,created_at,reporter_id").order("created_at", { ascending: false }).limit(6),
    db.from("moderation_audit_log").select("id,moderator_id,report_id,action,old_status,new_status,created_at").order("created_at", { ascending: false }).limit(6),
    db.rpc("admin_analytics_summary", { period_start: today, period_end: today }),
  ]);
  const metrics = summary && typeof summary === "object" ? summary : null;
  const dailyMetrics = todayAnalytics && typeof todayAnalytics === "object" ? todayAnalytics as any : null;
  const contextLoadError = summaryError || reportsError || auditError;
  const caseMetrics = [["new_cases", "New"], ["triage_cases", "Triage"], ["investigating_cases", "Investigating"], ["waiting_cases", "Waiting"]];
  const safetyMetrics = [["high_priority_unassigned", "High-priority unassigned"], ["multi_reporter_cases", "Multiple reporters"], ["pending_age_appeals", "Pending age appeals"]];
  const opsMetrics = [["active_users", "Active users"], ["deactivated_users", "Deactivated"], ["storage_failed", "Storage failures"], ["storage_pending", "Storage pending"], ["active_holds", "Retention holds"]];
  const displayMetric = (key: string) => contextLoadError ? "—" : Number(metrics?.[key] ?? 0).toLocaleString();

  return <AdminPage>
    <AdminHeader active="overview" eyebrow="Admin Center · Overview" title="Admin Center" description="Monitor moderation workload, platform activity, operational health, and administrator actions." isAdmin showNav />
    {contextLoadError && <p role="alert" className="notice notice-error mt-6">Some Admin Center data could not be loaded. Refresh before acting on these figures.</p>}

    <section className="mt-8" aria-labelledby="queue-heading">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="admin-eyebrow">Needs attention</p><h2 id="queue-heading" className="section-title mt-1">Moderation queue</h2></div><Link href="/app/admin/cases" className="text-sm font-semibold text-brand hover:underline">Review Mod Inbox →</Link></div>
      <div className="mt-4 grid overflow-hidden border-y border-black/10 bg-white/20 sm:grid-cols-2 lg:grid-cols-4">{caseMetrics.map(([key, label]) => <Link key={key} href={`/app/admin/cases?status=${key.replace("_cases", "")}`} className="border-b border-black/10 px-5 py-4 transition hover:bg-white/60 sm:border-r lg:border-b-0 lg:last:border-r-0"><p className="section-title-large">{displayMetric(key)}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-black/45">{label}</p></Link>)}</div>
      <div className="mt-4 grid gap-4 sm:grid-cols-3">{safetyMetrics.map(([key, label]) => <Link key={key} href={key === "pending_age_appeals" ? "/app/admin/age-appeals" : "/app/admin/cases"} className="flex items-center justify-between border border-black/10 bg-white/35 px-5 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><span className="text-sm text-black/65">{label}</span><span className="section-title">{displayMetric(key)}</span></Link>)}</div>
    </section>

    <section className="mt-10 grid gap-4 lg:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]" aria-label="Administrator overview">
      <div className="border border-black/10 bg-white/35 p-5 sm:p-6">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="admin-eyebrow">Platform activity</p><h2 id="today-heading" className="section-title mt-1">Today</h2><p className="mt-1 text-sm text-black/50">Read-only platform activity for {today}.</p></div><Link href="/app/admin/analytics?range=today" className="text-sm font-semibold text-brand hover:underline">Open analytics →</Link></div>
        {analyticsError ? <p role="alert" className="notice notice-error mt-5">Today&apos;s activity metrics could not be loaded. Open Analytics to retry.</p> : <div className="mt-5 grid overflow-hidden border-y border-black/10 bg-white/20 sm:grid-cols-2 xl:grid-cols-5">{[["online_now", "Online now", dailyMetrics?.users], ["active_in_period", "Active today", dailyMetrics?.users], ["new_registrations", "New registrations", dailyMetrics?.users], ["messages_sent", "Messages sent", dailyMetrics?.engagement], ["snail_mail_sent", "Snail Mail sent", dailyMetrics?.engagement]].map(([key, label, group]: any) => <div key={key} className="border-b border-black/10 px-4 py-4 last:border-b-0 sm:border-r xl:border-b-0 xl:last:border-r-0"><p className="section-title">{Number(group?.[key] ?? 0).toLocaleString()}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-black/45">{label}</p></div>)}</div>}
      </div>
      <div className="border border-black/10 bg-white/35 p-5 sm:p-6">
        <div className="flex items-baseline justify-between gap-4"><div><p className="admin-eyebrow">Operational status</p><h2 className="section-title mt-1">System health</h2></div><Link href="/app/admin/system" className="text-sm font-semibold text-brand hover:underline">Open system →</Link></div>
        <div className="mt-5 divide-y divide-black/10 border-y border-black/10">{opsMetrics.map(([key, label]) => <div key={key} className="flex items-center justify-between gap-4 py-3"><span className="text-sm text-black/60">{label}</span><span className="subsection-title">{displayMetric(key)}</span></div>)}</div>
        {!contextLoadError && Number(metrics?.storage_failed ?? 0) > 0 && <p className="mt-4 border-l-2 border-amber-500 px-3 py-2 text-sm text-amber-800">Storage cleanup has {metrics.storage_failed} failed item(s). Open System to review the queue before retrying.</p>}
      </div>
    </section>

    <div className="mt-10 grid gap-6 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,.9fr)]">
      <section className="border-t border-black/10 pt-7" aria-labelledby="reports-heading"><div className="flex items-baseline justify-between gap-4"><div><p className="admin-eyebrow">Trust &amp; safety</p><h2 id="reports-heading" className="section-title mt-1">Recent reports</h2></div><Link href="/app/admin/reports" className="text-sm font-semibold text-brand hover:underline">All reports</Link></div><div className="admin-table mt-4">{reportsError ? <p role="alert" className="p-6 text-sm text-red-700">Recent reports are unavailable. Refresh or open Reports to retry.</p> : (recentReports ?? []).length ? recentReports.map((report: any) => <Link key={report.id} href={`/app/admin/reports?report=${report.id}`} className="admin-row block"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-medium capitalize">{report.target_type} <span className="font-normal text-black/45">· {report.reason}</span></p><StatusChip value={report.status} tone={toneForStatus(report.status)} /></div><p className="mt-2 text-xs text-black/45">Report {report.id.slice(0, 8)} · {new Date(report.created_at).toLocaleString()}</p></Link>) : <p className="p-6 text-sm text-black/50">No recent reports.</p>}</div></section>
      <section className="border-t border-black/10 pt-7" aria-labelledby="activity-heading"><div className="flex items-baseline justify-between gap-4"><div><p className="admin-eyebrow">Accountability</p><h2 id="activity-heading" className="section-title mt-1">Recent activity</h2></div><Link href="/app/admin/audit" className="text-sm font-semibold text-brand hover:underline">Open audit log</Link></div><div className="admin-table mt-4">{auditError ? <p role="alert" className="p-6 text-sm text-red-700">Recent audit activity is unavailable. Open the Audit log to retry.</p> : (auditRows ?? []).length ? auditRows.map((entry: any) => <div key={entry.id} className="admin-row"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-medium capitalize">{entry.action.replaceAll("_", " ")}</p><time dateTime={entry.created_at} className="text-xs text-black/45">{new Date(entry.created_at).toLocaleString()}</time></div><p className="mt-1 text-xs text-black/50">{entry.moderator_id ? `Actor ${entry.moderator_id.slice(0, 8)}` : "System"} · {entry.old_status ?? "—"} → {entry.new_status ?? "—"}</p></div>) : <p className="p-6 text-sm text-black/50">No recent audit activity.</p>}</div></section>
    </div>

    <section className="mt-10 border-t border-black/10 pt-7" aria-labelledby="quick-heading"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="admin-eyebrow">Admin tools</p><h2 id="quick-heading" className="section-title mt-1">Common actions</h2></div><div className="flex gap-4 text-sm"><Link href="/app/admin/users" className="font-semibold text-brand hover:underline">Users</Link><Link href="/app/admin/staff" className="font-semibold text-brand hover:underline">Staff</Link></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Link href="/app/admin/cases?status=new" className="border border-black/10 bg-white/30 px-4 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><p className="font-semibold">Review new cases</p><p className="mt-1 text-xs text-black/50">Triage the oldest unreviewed moderation cases.</p></Link><Link href="/app/admin/age-appeals" className="border border-black/10 bg-white/30 px-4 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><p className="font-semibold">Age appeals</p><p className="mt-1 text-xs text-black/50">Review pending age-correction appeals.</p></Link><Link href="/app/admin/users" className="border border-black/10 bg-white/30 px-4 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><p className="font-semibold">User directory</p><p className="mt-1 text-xs text-black/50">Search accounts and open privileged account context.</p></Link><Link href="/app/admin/moderation-rules" className="border border-black/10 bg-white/30 px-4 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><p className="font-semibold">Detection rules</p><p className="mt-1 text-xs text-black/50">Review and manage automated moderation rules.</p></Link><Link href="/app/admin/audit?action=verification_metadata_view" className="border border-black/10 bg-white/30 px-4 py-4 transition hover:border-[#087456]/35 hover:bg-white/65"><p className="font-semibold">Verification review</p><p className="mt-1 text-xs text-black/50">Review audited verification-metadata access.</p></Link></div></section>
  </AdminPage>;
}
