/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import Link from "next/link";
import { requireAdmin } from "./guard";
import { AdminHeader, AdminPage, StatusChip, toneForStatus } from "./AdminChrome";

export default async function AdminCenter() {
  const { db } = await requireAdmin();
  const today = new Date().toISOString().slice(0, 10);
  const [{ data: summary, error: summaryError }, { data: recentReports, error: reportsError }, { data: auditRows, error: auditError }, { data: todayAnalytics, error: analyticsError }] = await Promise.all([
    db.rpc("admin_dashboard_summary"),
    db.from("reports").select("id,target_type,reason,status,created_at,reporter_id").order("created_at", { ascending: false }).limit(6),
    db.from("moderation_audit_log").select("id,moderator_id,report_id,action,old_status,new_status,created_at").order("created_at", { ascending: false }).limit(6),
    db.rpc("admin_analytics_summary", { period_start: today, period_end: today }),
  ]);
  const metrics = summary && typeof summary === "object" ? summary : null;
  const dailyMetrics = todayAnalytics && typeof todayAnalytics === "object" ? todayAnalytics as any : null;
  const contextLoadError = summaryError || reportsError || auditError;
  const caseMetrics = [["new_cases", "New"], ["triage_cases", "Triage"], ["investigating_cases", "Investigating"], ["waiting_cases", "Waiting"]];
  const safetyMetrics = [["high_priority_unassigned", "High priority"], ["multi_reporter_cases", "Multi-reporter"], ["pending_age_appeals", "Age appeals"]];
  const opsMetrics = [["active_users", "Active users"], ["deactivated_users", "Deactivated"], ["storage_failed", "Storage failures"], ["storage_pending", "Storage pending"], ["active_holds", "Retention holds"]];
  const displayMetric = (key: string) => contextLoadError ? "—" : Number(metrics?.[key] ?? 0).toLocaleString();

  return <AdminPage>
    <AdminHeader active="overview" eyebrow="Admin Center · Overview" title="Admin Center" description="Review queues, account context, and the decisions that keep pen-pals.net safe." isAdmin showNav />
    {contextLoadError && <p role="alert" className="mt-6 border-l-2 border-red-400 bg-red-50/40 px-3 py-2 text-sm text-red-700">Some administrator context could not be loaded. Refresh before relying on these figures.</p>}
    <section className="admin-section mt-8" aria-labelledby="queue-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="admin-eyebrow">Work queues</p><h2 id="queue-heading" className="admin-section-title mt-1">What needs attention</h2></div><Link href="/app/admin/cases" className="text-sm font-semibold text-[#087456] hover:underline">Open case queue →</Link></div><div className="mt-5 grid gap-0 border-y border-black/10 bg-white/20 sm:grid-cols-2 lg:grid-cols-4">{caseMetrics.map(([key, label]) => <Link key={key} href={`/app/admin/cases?status=${key.replace("_cases", "")}`} className="border-b border-black/10 px-4 py-4 transition hover:bg-white/60 lg:border-b-0 lg:border-r lg:last:border-r-0"><p className="font-serif text-3xl text-[#10231d]">{displayMetric(key)}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.12em] text-black/45">{label} cases</p></Link>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-3">{safetyMetrics.map(([key, label]) => <Link key={key} href={key === "pending_age_appeals" ? "/app/admin/age-appeals" : "/app/admin/cases"} className="flex items-center justify-between border border-black/10 bg-white/35 px-4 py-3 hover:bg-white/65"><span className="text-sm text-black/65">{label}</span><span className="font-serif text-xl text-[#10231d]">{displayMetric(key)}</span></Link>)}</div></section>
    <section className="admin-section mt-8" aria-labelledby="today-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="admin-eyebrow">Live pulse</p><h2 id="today-heading" className="admin-section-title mt-1">Today at a glance</h2><p className="mt-1 text-sm text-black/50">Read-only aggregate activity for {today}.</p></div><Link href="/app/admin/analytics?range=today" className="text-sm font-semibold text-[#087456] hover:underline">Open analytics →</Link></div>{analyticsError ? <p role="alert" className="mt-5 border-l-2 border-red-400 px-3 py-2 text-sm text-red-700">Today&apos;s analytics could not be loaded. Open Analytics to retry.</p> : <div className="mt-5 grid gap-0 border-y border-black/10 bg-white/20 sm:grid-cols-2 lg:grid-cols-5">{[["online_now", "Online now", dailyMetrics?.users], ["active_in_period", "Active today", dailyMetrics?.users], ["new_registrations", "New registrations", dailyMetrics?.users], ["messages_sent", "Messages sent", dailyMetrics?.engagement], ["snail_mail_sent", "Snail Mail sent", dailyMetrics?.engagement]].map(([key, label, group]: any) => <div key={key} className="border-b border-black/10 px-4 py-4 last:border-b-0 sm:border-r lg:border-b-0 lg:last:border-r-0"><p className="font-serif text-2xl text-[#10231d]">{Number(group?.[key] ?? 0).toLocaleString()}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.12em] text-black/45">{label}</p></div>)}</div>}</section>
    <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1.15fr)_minmax(0,.85fr)]"><section className="admin-section" aria-labelledby="reports-heading"><div className="flex items-baseline justify-between gap-4"><h2 id="reports-heading" className="admin-section-title">Recent reports</h2><Link href="/app/admin/reports" className="text-sm font-semibold text-[#087456] hover:underline">View all</Link></div><div className="admin-table mt-4">{reportsError ? <p role="alert" className="p-6 text-sm text-red-700">Recent reports could not be loaded.</p> : (recentReports ?? []).length ? recentReports.map((report: any) => <Link key={report.id} href={`/app/admin/reports?report=${report.id}`} className="admin-row block"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-medium capitalize">{report.target_type} <span className="font-normal text-black/45">· {report.reason}</span></p><StatusChip value={report.status} tone={toneForStatus(report.status)} /></div><p className="mt-2 text-xs text-black/45">Report {report.id.slice(0, 8)} · {new Date(report.created_at).toLocaleString()}</p></Link>) : <p className="p-6 text-sm text-black/50">No reports yet.</p>}</div></section><section className="admin-section" aria-labelledby="activity-heading"><div className="flex items-baseline justify-between gap-4"><h2 id="activity-heading" className="admin-section-title">Recent activity</h2><Link href="/app/admin/audit" className="text-sm font-semibold text-[#087456] hover:underline">Audit log</Link></div><div className="admin-table mt-4">{auditError ? <p role="alert" className="p-6 text-sm text-red-700">Recent activity could not be loaded.</p> : (auditRows ?? []).length ? auditRows.map((entry: any) => <div key={entry.id} className="admin-row"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-medium capitalize">{entry.action.replaceAll("_", " ")}</p><time dateTime={entry.created_at} className="text-xs text-black/45">{new Date(entry.created_at).toLocaleString()}</time></div><p className="mt-1 text-xs text-black/50">{entry.moderator_id ? `Actor ${entry.moderator_id.slice(0, 8)}` : "System"} · {entry.old_status ?? "—"} → {entry.new_status ?? "—"}</p></div>) : <p className="p-6 text-sm text-black/50">No moderation activity yet.</p>}</div></section></div>
    <section className="admin-section mt-10" aria-labelledby="operations-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="admin-eyebrow">Operations</p><h2 id="operations-heading" className="admin-section-title mt-1">Accountability and system health</h2></div><div className="flex gap-4 text-sm"><Link href="/app/admin/users" className="font-semibold text-[#087456] hover:underline">Users</Link><Link href="/app/admin/audit" className="font-semibold text-[#087456] hover:underline">Audit log</Link></div></div><div className="mt-5 grid gap-0 border-y border-black/10 bg-white/20 sm:grid-cols-2 lg:grid-cols-5">{opsMetrics.map(([key, label]) => <div key={key} className="border-b border-black/10 px-4 py-4 last:border-b-0 sm:border-r lg:border-b-0 lg:last:border-r-0"><p className="font-serif text-2xl text-[#10231d]">{displayMetric(key)}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.12em] text-black/45">{label}</p></div>)}</div>{!contextLoadError && Number(metrics?.storage_failed ?? 0) > 0 && <p className="mt-3 border-l-2 border-amber-500 px-3 py-2 text-sm text-amber-800">Storage cleanup has failed for {metrics.storage_failed} item(s). Review deployment logs before retrying.</p>}</section>
    <section className="admin-section mt-10" aria-labelledby="quick-heading"><h2 id="quick-heading" className="admin-section-title">Quick access</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Link href="/app/admin/cases?status=new" className="border border-black/10 bg-white/30 px-4 py-4 hover:bg-white/65"><p className="font-semibold">New cases</p><p className="mt-1 text-xs text-black/50">Start triage from the oldest open work.</p></Link><Link href="/app/admin/age-appeals" className="border border-black/10 bg-white/30 px-4 py-4 hover:bg-white/65"><p className="font-semibold">Age appeals</p><p className="mt-1 text-xs text-black/50">Review correction requests with a reason.</p></Link><Link href="/app/admin/users" className="border border-black/10 bg-white/30 px-4 py-4 hover:bg-white/65"><p className="font-semibold">User directory</p><p className="mt-1 text-xs text-black/50">Search account and verification context.</p></Link><Link href="/app/admin/moderation-rules" className="border border-black/10 bg-white/30 px-4 py-4 hover:bg-white/65"><p className="font-semibold">Detection rules</p><p className="mt-1 text-xs text-black/50">Admin-only triage configuration.</p></Link><Link href="/app/admin/audit?action=verification_metadata_view" className="border border-black/10 bg-white/30 px-4 py-4 hover:bg-white/65"><p className="font-semibold">Verification review</p><p className="mt-1 text-xs text-black/50">Open audited provider metadata events.</p></Link></div></section>
  </AdminPage>;
}
